version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - poc-net
    configs:
      - source: rabbitmq_conf
        target: /etc/rabbitmq/rabbitmq.conf

  uploader:
    image: jessebracque/poc-uploader:1.0
    networks:
      - poc-net
    deploy:
      replicas: 1
    secrets:
      - rabbitmq_user
      - rabbitmq_pass
    configs:
      - source: rabbitmq_host
        target: /run/configs/rabbitmq_host

  processor:
    image: jessebracque/poc-processor:1.0
    networks:
      - poc-net
    deploy:
      replicas: 1
    secrets:
      - rabbitmq_user
      - rabbitmq_pass
    configs:
      - source: rabbitmq_host
        target: /run/configs/rabbitmq_host

networks:
  poc-net:
    driver: overlay

secrets:
  rabbitmq_user:
    file: ./secrets/rabbitmq_user.txt
  rabbitmq_pass:
    file: ./secrets/rabbitmq_pass.txt

configs:
  rabbitmq_host:
    file: ./configs/rabbitmq_host.txt
  rabbitmq_conf:
    file: ./configs/rabbitmq.conf
