version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_volume:/data
    command: server /data --console-address ":9001"
    deploy:
      placement:
        constraints:
          - node.hostname == 2526-ICT-arch-nick-reul

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mydb
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname == 2526-ICT-arch-nick-reul

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password123
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    deploy:
      placement:
        constraints:
          - node.hostname == 2526-ICT-arch-nick-reul

volumes:
  minio_volume:
  postgres_volume:
  pgadmin_volume: